#!/bin/sh
basedir=$(dirname "$(echo "$0" | sed -e 's,\\,/,g')")

case `uname` in
    *CYGWIN*) basedir=`cygpath -w "$basedir"`;;
esac

if [ -x "$basedir/node" ]; then
  exec "$basedir/node"  "$basedir/../../../../../../vite@5.2.11_@types+node@20.12.11_sass@1.77.1/node_modules/vite/bin/vite.js" "$@"
else
  exec node  "$basedir/../../../../../../vite@5.2.11_@types+node@20.12.11_sass@1.77.1/node_modules/vite/bin/vite.js" "$@"
fi
