#
#   ASTER's CONFIG
#

# URL (url)
# ---
# Do not change this after your instance has begun federating!
# Start this with https:// or http:// and end it with a /
# e.g. https://as.example.com/
url: 'https://example.com/'

# PORT (port)
# ----
# Port that the instance will run on.
# e.g. 3000
port: 3000

# DATABASE HOST (dbhost)
# -------------
# Hostname you'd use to connect to the Postgres instance
# Typically, you won't need to change this.
# e.g. localhost
dbhost: localhost

# DATABASE NAME (dbname)
# -------------
# Name of the database to connect to
# e.g. aster
dbname: aster

# DATABASE USER (dbuser)
# -------------
# Name of the user to connect to the database as
# e.g. aster
dbuser: aster

# DATABASE PASSWORD (dbpass)
# -----------------
# Password of the user to connect to the database as
# Please randomly generate this!
dbpass: ''

# REDIS HOST (redishost)
# ----------
# Host to use to connect to your Redis instance.
# Typically, you won't need to change this.
redishost: localhost

# REDIS PORT (redisport)
# ----------
# Port to use to connect to your Redis instance.
# Typically, you won't need to change this.
redisport: 6379

# REDIS PREFIX (redisprefix)
# ------------
# Prefix to put in front of keys in Redis.
# Typically, you won't need to set this.
redisprefix: ''

# REDIS DATABASE (redisdb)
# ------------
# Database used within Redis.
# Typically, you won't need to set this if you don't expose
# your Redis instance.
redisdb: ''

# REDIS USERNAME (redisuser)
# --------------
# Username used for Redis authentication.
# Typically, you won't need to set this if you don't expose
# your Redis instance and require authentication.
redisuser: ''

# REDIS PASSWORD (redispw)
# --------------
# Password used for Redis authentication.
# Typically, you won't need to set this if you don't expose
# your Redis instance and require authentication.
redispw: ''

# DEBUG (debug)
# -----
# If debug mode is on. This will increase the detail of logs.
# e.g. false
debug: false

# LOGGING TYPE (logging)
# ------------
# How logs will be displayed in the command line.
# Options: json, fancy
logging: 'json'

# SAVE LOGS (savelogs)
# ---------
# If logs should be saved to a file.
# e.g. false
savelogs: false
