###########################
#   Aster Configuration   #
###########################

# URL where the instance should be accessed from
# !! do not change after you start federating !!
# eg https://example.com/
url: https://example.com/

# port to bind server to
# eg 9972
port: 9972

# options: open, approval, invite, closed
# eg 'invite'
registrations: 'invite'

# id format to use
# you don't need to change this unless migrating from a misskey derivative
# or just feel like it. i don't reccomend aid, meid, meidg, or objectid
# you can change this after begin federating, but i don't reccomend it
# options: aidx, aid, meid, meidg, objectid, ulid, uuidv4, uuidv7
# eg 'aidx'
id: 'aidx'

# locale to use in api responses
# see locale/index.json for options
# eg 'en_US'
locale: 'en_US'

# requires all GET requests to the instance's ap endpoints to be signed like
# inbox POSTS are. allows enforcing blocks more effectively
authorizedFetch: false

bubbleTimeline:
    # the bubble timeline is a timeline that includes the listed instance's
    # public posts. it's a nice way to make a smaller global timeline of
    # instances similar to yours.
    # eg true
    enabled: false
    # the instances hosts
    # eg example.com
    instances:
        -

workers:
    # number of processes to create to run the instance.
    # the number of cores your machine has or below is recommended.
    # eg 4
    count: 4

database:
    host: localhost
    port: 5432
    name: 'aster'
    user: 'aster'
    pass:

redis:
    host: localhost
    port: 6379
    prefix:
    database:
    user:
    pass:

cache:
    ap:
        enabled: true
        expiration: 150
    api:
        enabled: true
        expiration: 30
    meta:
        enabled: true
        expiration: 300

queue:
    inbox:
        attempts: 35
        backoff: 10000
        concurrency: 25
    deliver:
        attempts: 75
        backoff: 25000
        concurrency: 25
    backfill:
        attempts: 10
        backoff: 3600000
        concurrency: 25

timeline:
    maxObjects: 45

logging:
    http: true
    debug: false
    sql: false
    type: 'fancy'

router:
    frontend: true
    queue: true
    oapi: true
    swagger: true

metrics:
    enabled: true

security:
    blockedUserAgents:
        - ChatGPT-User
        - Meta-ExternalFetcher
        - Applebot-Extended
        - Bytespider
        - CCBot
        - ClaudeBot
        - Diffbot
        - FacebookBot
        - Google-Extended
        - GPTBot
        - Meta-ExternalAgent
        - omgili
        - Timpibot
        - Amazonbot
        - Applebot
        - OAI-SearchBot
        - PerplexityBot
        - anthropic-ai
        - Claude-Web
        - cohere-ai
        - ImagesiftBot

limits:
    soft:
        password: 1000
        cw: 5000
        note: 20000
        username: 500
        displayName: 500
        bio: 20000
        location: 1000
        birthday: 100
    hard:
        url: 10000
        key: 10000
        host: 25000
        cw: 50000
        note: 100000
        username: 2500
        displayName: 5000
        bio: 100000
        location: 5000
        birthday: 500
