#
#   ASTER's CONFIG
#

# URL (url)
# ---
# Do not change this after your instance has begun federating!
# Start this with https:// or http:// and end it with a /
# e.g. https://ap.example.com/
url: 'https://example.com/'

# PORT (port)
# ----
# Port that the instance will run on.
# e.g. 3000
port: 3000

# DATABASE HOST (dbhost)
# -------------
# Hostname you'd use to connect to the Postgres instance
# Typically, you won't need to change this.
# e.g. localhost
dbhost: localhost

# DATABASE NAME (dbname)
# -------------
# Name of the database to connect to
# e.g. aster
dbname: aster

# DATABASE USER (dbuser)
# -------------
# Name of the user to connect to the database as
# e.g. aster
dbuser: aster

# DATABASE PASSWORD (dbpass)
# -----------------
# Password of the user to connect to the database as
# Please randomly generate this!
dbpass:

# NODE NAME (nodename)
# ---------
# Name of your instance
# e.g. My Awesome Test Instance
nodename: 'Aster'

# NODE DESCRIPTION (nodedesc)
# ----------------
# Description of your instance
# e.g. An instance I'm using to test Aster
nodedesc: 'A fediverse instance running Aster'

# NODE COLOR (nodecolor)
# ----------
# Color to represent your instance
# Appears in places like Misskey instance ticker
# e.g. #9f96ff
nodecolor: '#9f96ff'

#
# ADMIN SETTINGS
# eventually this will be in the database
#

# REGISTRATIONS (a_registrations)
# -------------
# Allow registrations to your instance
# open: Anyone can register
# invite0: anyone can register if they have the multi-use code
# invite1: anyone can register if they have a one-time invite code
# closed: nobody can register
# Options: open, invite0, invite1, closed
a_registrations: 'closed'

# REGISTRATION CODE (a_invite0code)
# -----------------
# ONLY if your instance is set to invite0 for
# registrations, anyone can sign up with this code.
# I reccomend you randomly generate it like a password,
# otherwise it may be able to be bruteforced.
# If you use another registration type, leave this empty.
a_invite0code: ''
