#
#   ASTER's CONFIG
#

# URL (url)
# ---
# Do not change this after your instance has begun federating!
# Start this with https:// or http:// and end it with a /
# e.g. https://as.example.com/
url: 'https://example.com/'

# PORT (port)
# ----
# Port that the instance will run on.
# e.g. 3000
port: 3000

# DATABASE HOST (dbhost)
# -------------
# Hostname you'd use to connect to the Postgres instance
# Typically, you won't need to change this.
# e.g. localhost
dbhost: localhost

# DATABASE NAME (dbname)
# -------------
# Name of the database to connect to
# e.g. aster
dbname: aster

# DATABASE USER (dbuser)
# -------------
# Name of the user to connect to the database as
# e.g. aster
dbuser: aster

# DATABASE PASSWORD (dbpass)
# -----------------
# Password of the user to connect to the database as
# Please randomly generate this!
dbpass: ''

# REDIS HOST (redishost)
# ----------
# Host to use to connect to your Redis instance.
# Typically, you won't need to change this.
redishost: localhost

# REDIS PORT (redisport)
# ----------
# Port to use to connect to your Redis instance.
# Typically, you won't need to change this.
redisport: 6379

# REDIS PREFIX (redisprefix)
# ------------
# Prefix to put in front of keys in Redis.
# Typically, you won't need to set this.
redisprefix: ''

# REDIS DATABASE (redisdb)
# ------------
# Database used within Redis.
# Typically, you won't need to set this if you don't expose
# your Redis instance.
redisdb: ''

# REDIS USERNAME (redisuser)
# --------------
# Username used for Redis authentication.
# Typically, you won't need to set this if you don't expose
# your Redis instance and require authentication.
redisuser: ''

# REDIS PASSWORD (redispw)
# --------------
# Password used for Redis authentication.
# Typically, you won't need to set this if you don't expose
# your Redis instance and require authentication.
redispw: ''

# NODE NAME (nodename)
# ---------
# Name of your instance
# e.g. My Awesome Test Instance
nodename: 'Aster'

# NODE DESCRIPTION (nodedesc)
# ----------------
# Description of your instance
# e.g. An instance I'm using to test Aster
nodedesc: 'A fediverse instance running Aster'

# NODE COLOR (nodecolor)
# ----------
# Color to represent your instance
# Appears in places like Misskey instance ticker
# e.g. #9f96ff
nodecolor: '#9f96ff'

# MAINTAINER (maintainer)
# ----------
# Admin's name
# e.g. blueb
maintainer: ''

# MAINTAINER CONTACT (maintaineremail)
# ------------------
# Admin's contact email
# e.g. ihateblueb@proton.me
maintaineremail: ''

# DEBUG (debug)
# -----
# If debug mode is on. This will increase the detail of logs.
# e.g. false
debug: false

# LOGGING TYPE (logging)
# ------------
# How logs will be displayed in the command line.
# Options: json, fancy
logging: 'fancy'

# SAVE LOGS (savelogs)
# ---------
# If logs should be saved to a file.
# e.g. false
savelogs: false

#
# ADMIN SETTINGS
# eventually this will be in the database
#

# REGISTRATIONS (a_registrations)
# -------------
# Allow registrations to your instance
# open: Anyone can register
# invite0: anyone can register if they have the multi-use code
# invite1: anyone can register if they have a one-time invite code
# closed: nobody can register
# Options: open, invite0, invite1, closed
a_registrations: 'closed'

# REGISTRATION CODE (a_invite0code)
# -----------------
# ONLY if your instance is set to invite0 for
# registrations, anyone can sign up with this code.
# I reccomend you randomly generate it like a password,
# otherwise it may be able to be bruteforced.
# If you use another registration type, leave this empty.
a_invite0code: ''
#
# DESTRUCTIVE
# config options that may ruin your instance forever
#

# KILLSWITCH (d_killswitch)
# ----------
# The killswitch is for instances that are never returning.
# Your domain will be rendered fully unusable, and this instance
# will send out Delete activities and return 410 GONE to requests.
#
# It may take a while to do this. I reccomend you leave this up for
# a week or so.
#
# In order to enable, set d_killswitch to 'IKnowWhatIAmDoingAndIWantThisInstanceToDie'
#
