#
#   ASTER's CONFIG
#

# URL (url)
# ---
# Do not change this after your instance has begun federating!
# Start this with https:// or http:// and end it with a /
# e.g. https://ap.example.com/
url: 'https://as2.blueb.me/'

# PORT (port)
# ----
# Port that the instance will run on.
# e.g. 3000
port: 9970

# DATABASE HOST (dbhost)
# -------------
# Hostname you'd use to connect to the Postgres instance
# Typically, you won't need to change this.
# e.g. localhost
dbhost: localhost

# DATABASE NAME (dbname)
# -------------
# Name of the database to connect to
# e.g. aster
dbname: aster17

# DATABASE USER (dbuser)
# -------------
# Name of the user to connect to the database as
# e.g. aster
dbuser: aster

# DATABASE PASSWORD (dbpass)
# -----------------
# Password of the user to connect to the database as
# Please randomly generate this!
dbpass: 1210

# NODE NAME (nodename)
# ---------
# Name of your instance
# e.g. Aster
nodename: 'Database 17'

# NODE DESCRIPTION (nodedesc)
# ----------------
# Description of your instance
# e.g. An instance I'm using to test Aster
nodedesc: "Welcome. Welcome to Database 17. You have chosen or been chosen to relocate to one of our finest Postgres installations. I've thought so much of Database 17 that I elected to establish.. my testing instance here. In the container so thoughtfully provided by, our benefactors."

# NODE COLOR (nodecolor)
# ----------
# Color to represent your instance
# Appears in places like Misskey instance ticker
# e.g. #9f96ff
nodecolor: '#426e4c'

# DEBUG (debug)
# -----
# If debug mode is on. This will increase the detail of logs.
# e.g. false
debug: true

# LOGGING TYPE (logging)
# ------------
# How logs will be displayed in the command line.
# Options: json, fancy
logging: fancy

# SAVE LOGS (savelogs)
# ---------
# If logs should be saved to a file.
# e.g. false
savelogs: false
