#
#   ASTER's CONFIG
#

# URL (url)
# ---
# Do not change this after your instance has begun federating!
# Start this with https:// or http:// and end it with a /
# e.g. https://ap.example.com/
url: "https://"

# PORT (port)
# ----
# Port that the instance will run on.
# e.g. 3000
port: 3093

# DATABASE HOST (dbhost)
# -------------
# Hostname you'd use to connect to the Postgres instance
# Typically, you won't need to change this.
# e.g. localhost
dbhost: localhost

# DATABASE NAME (dbname)
# -------------
# Name of the database to connect to
# e.g. aster
dbname: aster

# DATABASE USER (dbuser)
# -------------
# Name of the user to connect to the database as
# e.g. aster
dbuser: aster

# DATABASE PASSWORD (dbpass)
# -----------------
# Password of the user to connect to the database as
# Please randomly generate this!
dbpass: 243298234

# NODE NAME (nodename)
# ---------
# Name of your instance
# e.g. My Awesome Test Instance
nodename: "aster test instance :3"