name: Test

on: [push]

jobs:
    build:
        runs-on: ubuntu-latest
        steps:
            - name: Checkout repository
              uses: actions/checkout@v3

            - name: Install pnpm
              run: npm install -g pnpm

            - name: Update submodules
              run: pnpm pull

            - name: Install dependencies
              run: pnpm install

            - name: Run tests
              run: pnpm test
